name=ESP32 BLE Keyboard
version=0.4.0
author=T-vK
maintainer=TheReider
sentence=Bluetooth LE Keyboard library for the ESP32.
paragraph=Bluetooth LE Keyboard library for the ESP32.
category=Communication
url=https://github.com/TheReider/ESP32-BLE-Keyboard.git
architectures=esp32
